// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjRJTCsBYnqQdQ-SGD49zdGfWPEJZHsk4',
    appId: '1:218766480547:web:2d3f01e053b08522a25b16',
    messagingSenderId: '218766480547',
    projectId: 'expense-tracker-a9c7b',
    authDomain: 'expense-tracker-a9c7b.firebaseapp.com',
    storageBucket: 'expense-tracker-a9c7b.firebasestorage.app',
    measurementId: 'G-77P3V3N03G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAznaS-YBihmge7jYbC5eO1M-EfkyoF9y0',
    appId: '1:218766480547:android:e9407369acb909fca25b16',
    messagingSenderId: '218766480547',
    projectId: 'expense-tracker-a9c7b',
    storageBucket: 'expense-tracker-a9c7b.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpE-Ljfbxre_Q0fenWGTkJpRtN5AbzvHw',
    appId: '1:218766480547:ios:7644790f7a4623bca25b16',
    messagingSenderId: '218766480547',
    projectId: 'expense-tracker-a9c7b',
    storageBucket: 'expense-tracker-a9c7b.firebasestorage.app',
    iosBundleId: 'com.example.expensTracker',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDpE-Ljfbxre_Q0fenWGTkJpRtN5AbzvHw',
    appId: '1:218766480547:ios:7644790f7a4623bca25b16',
    messagingSenderId: '218766480547',
    projectId: 'expense-tracker-a9c7b',
    storageBucket: 'expense-tracker-a9c7b.firebasestorage.app',
    iosBundleId: 'com.example.expensTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBjRJTCsBYnqQdQ-SGD49zdGfWPEJZHsk4',
    appId: '1:218766480547:web:611bd896f76cd986a25b16',
    messagingSenderId: '218766480547',
    projectId: 'expense-tracker-a9c7b',
    authDomain: 'expense-tracker-a9c7b.firebaseapp.com',
    storageBucket: 'expense-tracker-a9c7b.firebasestorage.app',
    measurementId: 'G-X4NGEBMEFZ',
  );
}
